[project]
name = "model-serve-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.13",
    "hypercorn>=0.17.3",
    "uvicorn>=0.34.3",
]
